# Generated by Django 6.0 on 2026-01-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.IntegerField()),
                ('StudentName', models.CharField(max_length=60)),
                ('StudentAge', models.IntegerField()),
                ('StudentEmail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
