# Generated by Django 5.2.8 on 2026-01-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statproj',
            name='image',
            field=models.ImageField(upload_to='static\\images'),
        ),
    ]
