# Generated by Django 6.0 on 2026-01-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeename', models.CharField(max_length=60)),
                ('Employeesalary', models.IntegerField()),
                ('Employeedept', models.CharField(max_length=60)),
            ],
        ),
    ]
