# Generated by Django 6.0 on 2026-01-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=15)),
                ('product_price', models.IntegerField()),
                ('product_quant', models.IntegerField()),
            ],
        ),
    ]
