# Generated by Django 6.0 on 2026-01-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=60)),
                ('employee_job', models.CharField(max_length=60)),
                ('employee_age', models.IntegerField()),
                ('employee_loc', models.CharField(max_length=60)),
            ],
        ),
    ]
