# Generated by Django 5.2.8 on 2026-01-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otpapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='mail',
            new_name='email',
        ),
    ]
