# Generated by Django 5.2.8 on 2026-01-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('ProductName', models.CharField(max_length=60)),
                ('ProdcutImage', models.URLField(max_length=255)),
                ('ProductPrice', models.IntegerField()),
                ('ProductQuant', models.IntegerField()),
            ],
        ),
    ]
