# Generated by Django 6.0 on 2026-01-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField()),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductImage', models.URLField(max_length=600)),
                ('ProductPrice', models.IntegerField()),
                ('ProductQuantity', models.IntegerField()),
            ],
        ),
    ]
