# Generated by Django 6.0 on 2026-01-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=60)),
                ('productimage', models.ImageField(upload_to='images')),
                ('productprice', models.IntegerField()),
                ('productquantity', models.IntegerField()),
            ],
        ),
    ]
